Repository code-guhaejo/CodeBlack, pull requests merged in 2024-06, with the labels that each got.

#10 [Feature] Local Login 서버와 연결, 회원가입 구현
  .idea/deploymentTargetDropDown.xml
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/RetrofitClient.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/api/LoginLocalService.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/model/SignInRequest.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/model/SignInResponse.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/model/SignUpRequest.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/model/SignUpResponse.kt
  app/src/main/java/com/guhaejo/codeblack/view/LoginActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/MainActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/SignUpActivity.kt
  app/src/main/res/layout/activity_signup.xml
Labels: Feature

#11 [Feature]ChatBot
  app/src/main/java/com/guhaejo/codeblack/CounselingFragment.kt
  app/src/main/java/com/guhaejo/codeblack/CounselinglistFragment.kt
  app/src/main/java/com/guhaejo/codeblack/HospitalFragment.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/RetrofitClient.kt
  app/src/main/java/com/guhaejo/codeblack/view/MessageAdapter.kt
  app/src/main/java/com/guhaejo/codeblack/widget/utils/Message.kt
  app/src/main/res/layout/chat_item.xml
Labels: Feature

#12 [Feature] my page
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feature

#14 [Feature] Google Maps 구현
  .gitignore
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/guhaejo/codeblack/HospitalFragment.kt
  app/src/main/java/com/guhaejo/codeblack/MapsFragment.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/logingoogle/LoginGoogle.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/logingoogle/api/LoginGoogleApi.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/RetrofitClient.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/api/LoginLocalApi.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/map/LocationApi.kt
  app/src/main/java/com/guhaejo/codeblack/repository/LoginRepository.kt
  app/src/main/java/com/guhaejo/codeblack/view/HospitalDetailActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/LoginActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/MainActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/SignUpActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: Feature

#16 [Bug] bottom navigation bar error fix
  app/src/main/java/com/guhaejo/codeblack/BottomNavActivity.kt
Labels: bug

#18 [Refactor] 영업 시간 정보 추가 및 전화 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/guhaejo/codeblack/CounselingFragment.kt
  app/src/main/java/com/guhaejo/codeblack/HospitalFragment.kt
  app/src/main/java/com/guhaejo/codeblack/MapsFragment.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/chat/api/ChatService.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/chat/api/MessageService.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/chat/model/ChatRequest.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/chat/model/MessageRequest.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/chat/model/MessageResponse.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/RetrofitClient.kt
  app/src/main/java/com/guhaejo/codeblack/data/remote/loginlocal/api/MessageService.kt
  app/src/main/java/com/guhaejo/codeblack/view/HospitalDetailActivity.kt
  app/src/main/java/com/guhaejo/codeblack/view/MainActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_maps.xml
Labels: Feature

#21 GoogleSignInClient 추가
  app/src/main/java/com/guhaejo/codeblack/data/remote/logingoogle/LoginGoogle.kt
Labels: Feature

#20 [Feature] Emerlistfragment 수정
  app/src/main/java/com/guhaejo/codeblack/EmerlistFragment.kt
  app/src/main/res/layout/fragment_emerlist.xml
Labels: Feature

#22 [Refactor]채팅 UI 변경
  app/src/main/res/layout/fragment_counseling.xml
  app/src/main/res/layout/fragment_emerlist.xml
Labels: Refactor

#24 CodeBlack 프로젝트 결과 보고서
  CodeBlack_프로젝트 결과 보고서.pdf
Labels: documentation

#25 Weekly Report
  WeeklyReport/전문-팀과제01-01팀.hwp
  WeeklyReport/전문-팀과제02-01팀.hwp
  WeeklyReport/전문-팀과제03-01팀.hwp
  WeeklyReport/전문-팀과제04-01팀.hwpx
  WeeklyReport/전문-팀과제09-01팀.hwp
  WeeklyReport/전문-팀과제11-01팀.hwp
  WeeklyReport/전문-팀과제05-01팀.hwp
  WeeklyReport/전문-팀과제06-01팀.hwp
  WeeklyReport/전문-팀과제07-01팀.hwp
  WeeklyReport/전문-팀과제08-01팀.hwp
  WeeklyReport/전문-팀과제10-01팀.hwp
  WeeklyReport/전문-팀과제12-01팀.hwp
Labels: documentation

#26 CodeBlack Storyboard
  storyboard/전문-01팀-스토리보드v1.hwp
  storyboard/전문-01팀-스토리보드v2.hwpx
  storyboard/전문-01팀-스토리보드v3.hwp
Labels: documentation
